src/Feature/Header/code/Models/HeaderModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BeerSorter.Feature.Header.Models
{
    public class HeaderModel
    {
        public string LogoID { get; set; }
        public MenuViewModel Page { get; set; }
    }
}

src/Feature/Header/code/Models/MenuViewModel.cs
using Sitecore.Data.Fields;
using Sitecore.Data.Items;
using Sitecore.Links;
using System.Collections.Generic;

namespace BeerSorter.Feature.Header.Models
{
    public class MenuViewModel
    {
        public Item MenuItem { get; set; }
        public string ItemLink { get; set; }
        public List<MenuViewModel> Children { get; set; }

        public MenuViewModel(Item menuItem)
        {
            this.MenuItem = menuItem;
            var children = menuItem.Children;
            this.ItemLink = LinkManager.GetItemUrl(menuItem);
            this.Children = new List<MenuViewModel>();
            foreach (Item item in children)
            {
                if (item.TemplateID == Templates.Home.HomePageTemplatesID)
                {
                    this.Children.Add(new MenuViewModel(item));
                }

            }
        }
    }
}

src/Feature/Header/code/Controllers/Base/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BeerSorter.Feature.Header.Controllers.Base
{
    public class BaseController
    {
    }
}

src/Feature/Header/code/Controllers/HeaderController.cs
using BeerSorter.Feature.Header.Models;
using Sitecore.Security.Authentication;
using System.Web.Mvc;

namespace BeerSorter.Feature.Header.Controllers
{
    public class HeaderController : Controller
    {
        // GET: Header
        public ActionResult Index()
        {
            var homeItem = Sitecore.Context.Database.GetItem(Templates.Home.HomeItemID);
            var headerModel = new HeaderModel
            {
                Page = new MenuViewModel(homeItem),
                LogoID = Templates.Header.Fields.LogoFieldID.ToString()
            };
            

            return View(headerModel);
        }
        public ActionResult Logout()
        {
            AuthenticationManager.Logout();
            return Redirect("/Beers");
        }
    }
}

src/Feature/Header/code/Views/Header/Index.cshtml
@using System.Web.Mvc.Html
@using Sitecore.Links
@using Sitecore.Mvc
@using Sitecore.Security.Authentication;
@using BeerSorter.Feature.Header.Controllers;
@model BeerSorter.Feature.Header.Models.HeaderModel

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href=@Model.Page.ItemLink>
        @*<image mediaid="{F2037C3C-AF8C-4D70-B794-EAD8440AF6D3}" alt="Logo Jpg" height="" width="" hspace="" vspace="" /> hard code *@
        @Html.Sitecore().Field(Model.LogoID, new { mh = "100", mw = "100" })
    </a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            @foreach (var item in @Model.Page.Children)
            {
                if (item.Children.Count > 0)
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            @item.MenuItem.Name
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            @foreach (var page in @item.Children)
                            {
                                <a class="dropdown-item" href="@page.ItemLink">@page.MenuItem.Name</a>
                                <div class="dropdown-divider"></div>
                            }


                        </div>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" href=@item.ItemLink>@item.MenuItem.Name</a>
                    </li>
                }

            }


        </ul>

        @*<form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>*@
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href='#'>@Sitecore.Context.User.Name.ToString();</a>
            </li>
            @{
                if (Sitecore.Context.User.IsInRole("extranet\\BeerUser"))
                {

                    <li class="nav-item">

                        <form method="post" action="@Url.Action("Logout", "Header")">
                            <input type="submit" value="Logout" id="Submit" class="btn btn-default" />
                        </form>
                    </li>
                }
                else
                {
                    <li class="nav-item">
                        <a class="nav-link" href="/Login">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Registration">Sign Up</a>
                    </li>

                }
            }
        </ul>
    </div>
</nav>